manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-beyboard-hillside38
      url-base: https://github.com/Louissundronning
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-beyboard-hillside38
      remote: zmk-beyboard-hillside38_base
      revision: main
  self:
    path: config